version: '3.8'
services:
  choresawards:
    build: .
    ports:
      - "3112:3000"
    volumes:
      - .:/app
    environment:
      - TZ=Australia/Adelaide  # Adjust this to your actual timezone
    restart: always